### ISSUE TITLE
Broken in Firefox 32 

### ISSUE THREAD

**Issue by Herst** [philikon/VerticalTabs#37]
Broken in current Firefox beta (32).

**Comment by Herst** [comment]
And now it's final.

**Comment by averageapps** [comment]
I can confirm. The Tabs are now ordered horizontally in the sidebabar, making them inaccessible.

I can barely imagine browsing the web efficiently without this add-on. Does anyone know why it broke?

**Comment by Cheekysoft** [comment]
Disabling and enabling the addon does appear to cause the layout to go back to vertical. There also appears to be some stability problems, though.

**Comment by averageapps** [comment]
Disabling/enabling and even removing and reinstalling the add-on does nothing for me, unfortunately. Tabs are still horizontal inside the sidebar.
(Firefox 32.0 final on Arch Linux. Same behavior on 35.0 nightly)

**Comment by averageapps** [comment]
Until this is fixed, I recommend either using Firefox 31 ESR or Tree Style Tab: https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/.
This addon is not the same of course, but by setting the maximum indentation level to 1 (I am not a fan of complicated trees) and changing a few other things, you get a relatively similar behavior to VerticalTabs, and it works in recent Firefox versions on both Linux and Windows.

**Comment by guzul** [comment]
Pano extension works, unfortunately teramako (author) removed it from mozilla addons site.
here is the repository, but it's not packed.
https://github.com/teramako/Pano

**Comment by Jorilx** [comment]
I've just installed a version of VerticalTabs from [this fork](https://github.com/darrinhenein/VerticalTabs/raw/master/VerticalTabs.xpi) and it looks like it's working as expected

**Comment by guzul** [comment]
Great, thanks for the link :)
And by the way this guy works for mozilla :)
https://github.com/darrinhenein/VerticalTabs/

**Comment by illtellyoulater** [comment]
The forked version of Vertical Tabs too seems to not work anymore with newer Firefox versions...

Also.. do not use Tree Style Tab! 
I was using Session Manager extension too (like many of you I guess) and at some point it will mess up with it and will make it not save your last working session! Which can easily mean 100 tabs for me..

I wish it wasn't as much buggy as it is because it seem to be the only (at-least-temporarily) working vertical tab solution for Firefox, but again, for some reason will mess up with your windows/tabs sessions and then good luck fishing in your chronology.

**Comment by illtellyoulater** [comment]
And I confirm Pano it's working! And it has way more features! It even shows a tab popup screenshot on mouse over! Too bad it's not listed in mozilla addons...

**Comment by Croydon** [comment]
For all the people who still care after such a long time: https://github.com/Croydon/vertical-tabs-reloaded/ :)

**Comment by illtellyoulater** [comment]
I switched to Chrome + Tab Outliner
